#pragma once

#define DGENGINE_DEFAULT_SIZE_X 640
#define DGENGINE_DEFAULT_SIZE_Y 480

#define DGENGINE_MIN_SIZE_X 640
#define DGENGINE_MIN_SIZE_Y 480

#define DGENGINE_REF_SIZE_X 640
#define DGENGINE_REF_SIZE_Y 480
